### ISSUE TITLE
gRPC error in Storage Write API implementation

### ISSUE THREAD

**Issue by jclarysse** [Aiven-Open/bigquery-connector-for-apache-kafka#31]
After enabling [beta feature Storage Write API](https://github.com/Aiven-Open/bigquery-connector-for-apache-kafka/releases/tag/v2.6.0), a user is experiencing the following gRPC error:
```
ERROR Encountered unrecoverable failure (com.wepay.kafka.connect.bigquery.write.storage.StorageWriteApiBase:432)
com.wepay.kafka.connect.bigquery.exception.BigQueryStorageWriteApiConnectException: 
  Failed to write rows on table projects/<redacted_project>/datasets/<redacted_dataset>/tables/<redacted_table> due to com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection to server broken (OnChannelError)
	at com.wepay.kafka.connect.bigquery.write.storage.StorageWriteApiBase.writeBatch(StorageWriteApiBase.java:220)
	at com.wepay.kafka.connect.bigquery.write.storage.StorageWriteApiBase.initializeAndWriteRecords(StorageWriteApiBase.java:136)
	at com.wepay.kafka.connect.bigquery.write.storage.StorageWriteApiWriter.run(StorageWriteApiWriter.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask$MdcContextThreadFactory.lambda$newThread$0(BigQuerySinkTask.java:774)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection to server broken (OnChannelError)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:571)
	at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:53)
	at com.wepay.kafka.connect.bigquery.write.storage.StorageWriteApiBase.writeBatch(StorageWriteApiBase.java:185)
	... 6 more
Caused by: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection to server broken (OnChannelError)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:84)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:148)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection to server broken (OnChannelError)
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 14 more
```
The user suspects that this happens when there are more than one thread in the sink connector task that are trying to append rows and the default stream connection is being renewed simultaneously.

As the gRPC error seems to be occurring at low-level, I wonder if upgrading grpc-google-cloud-bigquerystorage-v1 lib to latest version could help resolve this.

**Comment by jclarysse** [comment]
I was informed that among multiple connector instances using similar configuration (3 tasks each), the issue only occurred for one specific instance and destination table. 
Also, restarting the connector resolved it and then the error didn't appear again. This confirms an edge-case that is probably hard to reproduce but not too urgent to solve.
